# parameters for the pre-trained versions of BrainOmni
# (a multitask foundation model for EEG and MEG)

# Basic configuration
seed: 42
master_port: 51901
multitask: false   # set to true to fine-tune with training samples from all datasets.
model_type: brainomni
fs: 256

# Data configuration
data:
  batch_size: 64
  num_workers: 1
  datasets:
    tuab: finetune
    seed: finetune_sub_dependent
    hmc: finetune
    # ...

# Model configuration
model:
  # Directory containing model_cfg.json and BrainOmni.pt
  pretrained_path: /data/lyh/model_weights/BrainOmni/tiny

  normalize_input: true
  normalize_position: true
  allow_missing_positions: false  # set to true if allow missing positions to be filled with zeros

  freeze_tokenizer: false

  # add architecture-related parameters as well if the
  # architecture is different from the public pre-trained version of BrainOmni

  # Classifier head configuration
  classifier_head:
    head_type: avg_pool # options: avg_pool, attention_pool, dual_stream_fusion, flatten_mlp, flatten_linear

    hidden_dims: [128]
    dropout: 0.3

# Training configuration
training:
  max_epochs: 30
  weight_decay: 0.01
  max_grad_norm: 1.0

  # learning rate-related parameters (important in parameter searching)
  lr_schedule: cosine
  max_lr: 5e-4
  min_lr: 5e-5
  encoder_lr_scale: 0.5
  # learning rate warm-up
  warmup_epochs: 3
  warmup_scale: 1e-1

  freeze_encoder: false

  # LoRA configuration
  lora:
    use_lora: false
    lora_r: 8
    lora_alpha: 16
    lora_dropout: 0.0
    lora_target_modules: [default]
    lora_exclude_modules: null
    # Options: default, full, attention, ffn
    lora_target_type: default
    # Options: transformer, full
    lora_scope: transformer
    lora_lr_scale: 1.0

# Logging configuration
logging:
  experiment_name: brainomni

  ckpt_interval: 10

  # local logging
  run_dir: assets/run

  # cloud logging
  use_cloud: true
  cloud_backend: wandb
  offline: false

  tags:
    - brainomni
    - uni
    - avg_pool
    - full
