seed: 42
multitask: false
model_type: minirocket

data:
  datasets:
    tuab: finetune
    # ... 
  batch_size: 256
  num_workers: 2

model:
  ridge_alphas:
    - 0.001
    - 0.01
    - 0.1
    - 1.0
    - 10.0
    - 100.0
    - 1000.0
  ridge_selection_metric: balanced_accuracy
  minirocket_source_path: /path/to/minirocket/repo
  minirocket_num_features: 10000
  minirocket_max_dilations_per_kernel: 32

logging:
  experiment_name: minirocket
  run_dir: assets/run
  use_cloud: false
  outputs:
    - csv
